### ISSUE TITLE
Savedata does not store properly on Linux

### ISSUE THREAD

**Issue by jet082** [Andoryuuta/Erupe#35]
Currently, the save data does not store itself in the directory savedata on Linux. Instead, it generates files named things like ``"savedata\1604271585_hunternavi.bin"`` (despite appearances this is a single file - and not a 'file in a directory.' The "\\" is part of the filename). These files sit in the root directory alongside, but not inside, the savedata directory.

I think this is a Linux '/' vs a Windows '\\' distinction problem.

I believe this has to do with the following line: https://github.com/Andoryuuta/Erupe/blob/a4ab2280467636341b2fbb4c9686d3d1bdc36056/server/channelserver/handlers.go#L1131

**Comment by Andoryuuta** [comment]
This should be fixed in 68270c54.

In the first place, this `dumpSaveData` method was added as a quick hack/workaround for still unknown save-data corruption issues.
